pekko {
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  loglevel = "DEBUG"
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"

  http.server.idle-timeout = 90 s
  http.server.request-timeout = 60 s
  actor {
    debug {
      unhandled = on
      fsm = on
    }
    allow-java-serialization = on
  }
}

pekko.kafka {
  bootstrapServers = "localhost:9092"
  bootstrapServers = ${?KAFKA_HOST}
  applicationId = "symptoms-extractor"

  common-topics {
    dlq-topic = "dlq.topic"
    errors-topic = "errors.topic"
  }

  patient-notes-topics {
    notes-topic-in = "patient-notes.v1"
    notes-topic-out = "patient-notes.normalized.v1"
    symptoms-extracted-topic = "symptoms.extracted.v1"
  }

  producer {
    # Tuning parameter of how many sends that can run in parallel.
    parallelism = 100

    kafka-clients {
      sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\""${?KAFKA_USERNAME}"\"password=\""${?KAFKA_PASSWORD}"\";"
      security.protocol = "PLAINTEXT"
      security.protocol = ${?KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism = ""
      sasl.mechanism = ${?KAFKA_SASL_MECHANISM}

      retries = 3
      connections.max.idle.ms = 60000
      metadata.max.idle.ms = 60000
      metadata.max.age.ms = 60000
    }

    data-buffer = 1
    data-buffer = ${?DATA_BUFFER}
    close-timeout = 60s
    use-dispatcher = "pekko.kafka.default-dispatcher"
  }

  consumer {
    kafka-clients {
      enable.auto.commit = false
      auto.offset.reset = "earliest"
      isolation.level = "read_committed"
      group.id = "symptoms-extractor-consumer-group"
      connections.max.idle.ms = 60000
    }
  }
}

symptoms.extractor {
}
